# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostitem', '0002_auto_20160120_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlost',
            old_name='m_added_date',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='itemlost',
            old_name='m_creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='itemlost',
            old_name='m_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='itemlost',
            old_name='m_whereFound',
            new_name='whereFound',
        ),
    ]
