# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostitem', '0003_auto_20160120_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlost',
            old_name='whereFound',
            new_name='where_was_found',
        ),
    ]
