# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lostitem', '0004_auto_20160120_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemlost',
            name='creator',
        ),
        migrations.AddField(
            model_name='itemlost',
            name='where_is_stored',
            field=models.CharField(default='in the kitchen', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemlost',
            name='color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lostitem.Colors'),
            preserve_default=False,
        ),
    ]
