# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostitem', '0005_auto_20160125_2259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
    ]
